In [1]:
import pandas as pd
df = pd.read_csv("../data/Advertising.csv", index_col=0)
df.head()


TV  radio  newspaper  sales
1  230.1   37.8       69.2   22.1
2   44.5   39.3       45.1   10.4
3   17.2   45.9       69.3    9.3
4  151.5   41.3       58.5   18.5
5  180.8   10.8       58.4   12.9

In [2]:
print(f"{df.shape[0]} samples")
print(f"{df.shape[1]} featurs")

200 samples
4 featurs


divde data into X and Y

In [3]:
X, y = df.drop("sales", axis="columns"), df["sales"]
X

TV  radio  newspaper
1    230.1   37.8       69.2
2     44.5   39.3       45.1
3     17.2   45.9       69.3
4    151.5   41.3       58.5
5    180.8   10.8       58.4
..     ...    ...        ...
196   38.2    3.7       13.8
197   94.2    4.9        8.1
198  177.0    9.3        6.4
199  283.6   42.0       66.2
200  232.1    8.6        8.7

[200 rows x 3 columns]

In [4]:
y

1      22.1
2      10.4
3       9.3
4      18.5
5      12.9
       ... 
196     7.6
197     9.7
198    12.8
199    25.5
200    13.4
Name: sales, Length: 200, dtype: float64

In [5]:
type(y),type(X)

(pandas.core.series.Series, pandas.core.frame.DataFrame)

In [6]:
## Scikit-learn steps
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33, random_state=42
)

X_train

TV  radio  newspaper
43   293.6   27.7        1.8
190   18.7   12.1       23.4
91   134.3    4.9        9.3
137   25.6   39.0        9.3
52   100.4    9.6        3.6
..     ...    ...        ...
107   25.0   11.0       29.7
15   204.1   32.9       46.0
93   217.7   33.5       59.0
180  165.6   10.0       17.6
103  280.2   10.1       21.4

[134 rows x 3 columns]

In [7]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.33, random_state=42
   )

print(f"{X_train.shape=}")
print(f"{y_train.shape=}")
print(f"{X_test.shape=}")
print(f"{y_test.shape=}")



X_train.shape=(134, 3)
y_train.shape=(134,)
X_test.shape=(66, 3)
y_test.shape=(66,)


In [8]:
X_train.head()

TV  radio  newspaper
43   293.6   27.7        1.8
190   18.7   12.1       23.4
91   134.3    4.9        9.3
137   25.6   39.0        9.3
52   100.4    9.6        3.6

In [9]:
y_train.head()

43     20.7
190     6.7
91     11.2
137     9.5
52     10.7
Name: sales, dtype: float64

In [10]:
##2.Feature scaling

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
type(scaler)

sklearn.preprocessing._data.MinMaxScaler

In [11]:
scaler

MinMaxScaler()

In [12]:
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_train.min() = np.float64(0.0)
scaled_X_train.max() = np.float64(1.0)
scaled_X_test.min() = np.float64(0.005964214711729622)
scaled_X_test.max() = np.float64(1.1302186878727631)


In [13]:
from sklearn.model_selection import train_test_split


X_train, X_test, y_train, y_test = train_test_split(
   X, y, test_size=0.33, random_state=42
   )

print(f"{X_train.shape=}")
print(f"{y_train.shape=}")
print(f"{X_test.shape=}")
print(f"{y_test.shape=}")



X_train.shape=(134, 3)
y_train.shape=(134,)
X_test.shape=(66, 3)
y_test.shape=(66,)


In [14]:
scaled_X_train[:5]

array([[0.99053094, 0.55846774, 0.01491054],
       [0.06087251, 0.24395161, 0.22962227],
       [0.45180927, 0.09879032, 0.08946322],
       [0.08420697, 0.78629032, 0.08946322],
       [0.33716605, 0.19354839, 0.03280318]])

In [15]:
type(scaled_X_train)

numpy.ndarray

In [16]:
##LINEAR REGRESSION

from sklearn.linear_model import LinearRegression

model = LinearRegression()
model 

LinearRegression()

In [17]:
model.fit(scaled_X_train, y_train)
print(f"Parameters or weights: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Parameters or weights: [13.20747617  9.75285112  0.61108329]
Intercept: 2.79115951962436


In [18]:
##4.Prediction

sample_features = scaled_X_test[0].reshape(1, -1)
sample_features

array([[0.54988164, 0.63709677, 0.52286282]])

In [19]:
model.predict(sample_features)

array([16.58673085])

In [20]:
y_test.iloc[0]

np.float64(16.9)

In [21]:
## predict on whole test data

y_pred = model.predict(scaled_X_test)
y_pred

array([16.58673085, 21.18622524, 21.66752973, 10.81086512, 22.25210881,
       13.31459455, 21.23875284,  7.38400509, 13.43971113, 15.19445383,
        9.01548612,  6.56945204, 14.4156926 ,  8.93560138,  9.56335776,
       12.10760805,  8.86091137, 16.25163621, 10.31036304, 18.83571624,
       19.81058732, 13.67550716, 12.45182294, 21.58072583,  7.67409148,
        5.67090757, 20.95448184, 11.89301758,  9.13043149,  8.49435255,
       12.32217788,  9.99097553, 21.71995241, 12.64869606, 18.25348116,
       20.17390876, 14.20864218, 21.02816483, 10.91608737,  4.42671034,
        9.59359543, 12.53133363, 10.14637196,  8.1294087 , 13.32973122,
        5.27563699,  9.30534511, 14.15272317,  8.75979349, 11.67053724,
       15.66273733, 11.75350353, 13.21744723, 11.06273296,  6.41769181,
        9.84865789,  9.45756213, 24.32601732,  7.68903682, 12.30794356,
       17.57952015, 15.27952025, 11.45659815, 11.12311877, 16.60003773,
        6.90611478])

In [22]:
y_test.iloc[:5]

96     16.9
16     22.4
31     21.4
159     7.3
129    24.7
Name: sales, dtype: float64

In [23]:
## 5. Evaluate

from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test,y_pred)
rmse = np.sqrt(mse)

print(f"{mae}")
print(f"{mse}")
print(f"{rmse}")


1.4937750024728984
3.72792833068152
1.9307843822347228


In [24]:
# Suppose you want to test: TV=100, Radio=50, Newspaper=20
my_sample = np.array([[100, 50, 20]])

# Scale it with the same scaler you fitted on training data
scaled_my_sample = scaler.transform(my_sample)

# Predict with the trained model
prediction = model.predict(scaled_my_sample)
print("Predicted Sales:", prediction[0])


Predicted Sales: 17.17757455475855


c:\Users\alans\Documents\GitHub\ai_engineering_malik_alansi\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(


In [25]:
# Predict all test samples
y_pred = model.predict(scaled_X_test)

# Show first 10 actual vs predicted
for actual, pred in zip(y_test[:10], y_pred[:10]):
    print(f"Actual: {actual:.2f}, Predicted: {pred:.2f}")


Actual: 16.90, Predicted: 16.59
Actual: 22.40, Predicted: 21.19
Actual: 21.40, Predicted: 21.67
Actual: 7.30, Predicted: 10.81
Actual: 24.70, Predicted: 22.25
Actual: 12.60, Predicted: 13.31
Actual: 22.30, Predicted: 21.24
Actual: 8.40, Predicted: 7.38
Actual: 11.50, Predicted: 13.44
Actual: 14.90, Predicted: 15.19
