In [73]:
import pandas as pd 

# relative path
df = pd.read_csv("../data/house_prices.csv")
df.head()

date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912   
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050   
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947   
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030   
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500   

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955   
1     2.0           0     4          5        3370            280      1921   
2     1.0           0     0          4        1930              0      1966   
3     1.0           0     0          4        1000           1000      1963   
4     1.0           0     0          4        1140            800      1976   

   yr_renovated                    street       city  statezip country  
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA  
1             0           709 W Blaine St    Seattle  WA 98119     USA  
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA  
3             0           857 170th Pl NE   Bellevue  WA 98008     USA  
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [74]:
df_cleaned = df.drop(
    ["country", "statezip", "city", "street", "date"], axis="columns"
)  # view?

df_cleaned["yr_renovated"] = df_cleaned.apply(
    lambda row: row["yr_built"] if not row["yr_renovated"] else row["yr_renovated"], axis=1
)
df_cleaned.head()

price  bedrooms  bathrooms  sqft_living  sqft_lot  floors  waterfront  \
0   313000.0       3.0       1.50         1340      7912     1.5           0   
1  2384000.0       5.0       2.50         3650      9050     2.0           0   
2   342000.0       3.0       2.00         1930     11947     1.0           0   
3   420000.0       3.0       2.25         2000      8030     1.0           0   
4   550000.0       4.0       2.50         1940     10500     1.0           0   

   view  condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0     0          3        1340              0      1955        2005.0  
1     4          5        3370            280      1921        1921.0  
2     0          4        1930              0      1966        1966.0  
3     0          4        1000           1000      1963        1963.0  
4     0          4        1140            800      1976        1992.0

In [75]:
# feature matrix and label vector 
X, y = df_cleaned.drop("sqft_living", axis=1), df_cleaned["sqft_living"]

X.head()

price  bedrooms  bathrooms  sqft_lot  floors  waterfront  view  \
0   313000.0       3.0       1.50      7912     1.5           0     0   
1  2384000.0       5.0       2.50      9050     2.0           0     4   
2   342000.0       3.0       2.00     11947     1.0           0     0   
3   420000.0       3.0       2.25      8030     1.0           0     0   
4   550000.0       4.0       2.50     10500     1.0           0     0   

   condition  sqft_above  sqft_basement  yr_built  yr_renovated  
0          3        1340              0      1955        2005.0  
1          5        3370            280      1921        1921.0  
2          4        1930              0      1966        1966.0  
3          4        1000           1000      1963        1963.0  
4          4        1140            800      1976        1992.0

In [76]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.33 #, random_state=42
)
print(f"{y_train.shape = }")
print(f"{X_test.shape = }")
print(f"{y_test.shape = }")

y_train.shape = (3082,)
X_test.shape = (1518, 12)
y_test.shape = (1518,)


In [77]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [78]:
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

print(f"{scaled_X_train.min() = }")
print(f"{scaled_X_train.max() = }")
print(f"{scaled_X_test.min() = }")
print(f"{scaled_X_test.max() = }")

scaled_X_train.min() = np.float64(0.0)
scaled_X_train.max() = np.float64(1.0)
scaled_X_test.min() = np.float64(-6.148033467658553e-05)
scaled_X_test.max() = np.float64(1.1851851851851851)


In [79]:
from sklearn.linear_model import LinearRegression

# instantiate an instance from LinearRegression class
model = LinearRegression()
model.fit(scaled_X_train, y_train)
print(f"Parameters or weights: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Parameters or weights: [ 2.17536034e-11 -3.63797881e-12 -1.17032536e-12  4.12261135e-12
  1.01709599e-13 -1.02907874e-12  4.95412635e-13 -2.42700328e-12
  7.65000000e+03  4.82000000e+03 -1.56719704e-12  1.25019598e-12]
Intercept: 370.0000000000041


In [80]:
model.fit(scaled_X_train, y_train)
print(f"Parameters or weights: {model.coef_}")
print(f"Intercept: {model.intercept_}")

Parameters or weights: [ 2.17536034e-11 -3.63797881e-12 -1.17032536e-12  4.12261135e-12
  1.01709599e-13 -1.02907874e-12  4.95412635e-13 -2.42700328e-12
  7.65000000e+03  4.82000000e+03 -1.56719704e-12  1.25019598e-12]
Intercept: 370.0000000000041


In [81]:
X_test.iloc[0]

price            495000.0
bedrooms              3.0
bathrooms             2.5
sqft_lot           1548.0
floors                3.0
waterfront            0.0
view                  0.0
condition             3.0
sqft_above         1750.0
sqft_basement         0.0
yr_built           2013.0
yr_renovated       1923.0
Name: 1420, dtype: float64

In [82]:
sample_features = scaled_X_test[0].reshape(1, -1)
sample_features

array([[1.86160211e-02, 3.33333333e-01, 3.70370370e-01, 7.86203068e-04,
        8.00000000e-01, 0.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        1.80392157e-01, 0.00000000e+00, 9.91228070e-01, 2.01754386e-01]])

In [83]:
model.predict(sample_features)

array([1750.])

In [84]:
y_pred = model.predict(scaled_X_test)
y_pred[:5]

array([1750., 1450.,  940., 2680., 1610.])

In [85]:
from sklearn.metrics import mean_absolute_error, mean_squared_error
import numpy as np 

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f"{mae = }")
print(f"{mse = }")
print(f"{rmse = }")



mae = 9.577629276698858e-13
mse = 1.5868662943700851e-24
rmse = np.float64(1.2597088133255578e-12)


In [ ]:
import numpy as np

my_sample = np.array([[313000.0,3.0,1.50,1340,7912,1.5,0,0,3,1340,1955,2005.0]])


scaled_my_sample = scaler.transform(my_sample)

prediction = model.predict(scaled_my_sample)
print("Predicted sqft_living:", prediction[0])


Predicted sqft_living: 1343.0000000003247


c:\Users\alans\Documents\GitHub\ai_engineering_malik_alansi\.venv\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
